<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120507100117 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE archive ADD archived_user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE archive ADD CONSTRAINT FK_D5FC5D9C522DA38B FOREIGN KEY (archived_user_id) REFERENCES user(id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_D5FC5D9C522DA38B ON archive (archived_user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE archive DROP FOREIGN KEY FK_D5FC5D9C522DA38B");
        $this->addSql("DROP INDEX IDX_D5FC5D9C522DA38B ON archive");
        $this->addSql("ALTER TABLE archive DROP archived_user_id");
    }
}
