<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120503142150 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE archive (id INT AUTO_INCREMENT NOT NULL, created_user_id INT DEFAULT NULL, last_edited_user_id INT DEFAULT NULL, board_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, created DATETIME NOT NULL, edited DATETIME NOT NULL, sorting INT NOT NULL, duration INT NOT NULL, group1 VARCHAR(100) DEFAULT NULL, group2 VARCHAR(100) DEFAULT NULL, group3 VARCHAR(100) DEFAULT NULL, INDEX IDX_D5FC5D9CE104C1D3 (created_user_id), INDEX IDX_D5FC5D9C2CDA43A (last_edited_user_id), INDEX IDX_D5FC5D9CE7EC5785 (board_id), PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE archive ADD CONSTRAINT FK_D5FC5D9CE104C1D3 FOREIGN KEY (created_user_id) REFERENCES user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE archive ADD CONSTRAINT FK_D5FC5D9C2CDA43A FOREIGN KEY (last_edited_user_id) REFERENCES user(id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE archive ADD CONSTRAINT FK_D5FC5D9CE7EC5785 FOREIGN KEY (board_id) REFERENCES board(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE archive");
    }
}
